### ISSUE TITLE
Cleanups

### ISSUE THREAD

**Issue by tshort** [schlichtanders/Traits.jl#1]
The main README could use some cleanups. There's code at the top that's not formatted right, so it looks bad in the browser.

In the Performance section at the bottom, there's some code that I think needs a `@traits` as indicated in the README under `/test`.

**Comment by schlichtanders** [comment]
Thanks a lot for spotting and mentioning.

I will have time today in the evening, bit of you like, feel encouraged to open a small pull request for it

**Comment by schlichtanders** [comment]
fixed it now, I hope everything is fine now
