### ISSUE TITLE
maybe rename the archive before the release

### ISSUE THREAD

**Issue by JeffreySarnoff** [schlichtanders/Traits.jl#7]
It's your call, of course. As you know there are some other trait packages out there: [SimpleTraits.jl](https://github.com/mauro3/SimpleTraits.jl), [BinaryTraits.jl](https://github.com/tk3369/BinaryTraits.jl), [CanonicalTraits.jl](https://github.com/thautwarm/CanonicalTraits.jl), for example.  We all want to converge on a `Traits.jl`; if you named this package `_Traits.jl` (fill in the _) that may make the process easier. Your package looks very promising.

**Comment by schlichtanders** [comment]
Thank you very much for the suggestion. I agree, that the kind of traits currently out there are quite different.
I am going to think about a name.

Also thanks for a pointer to CanonicalTraits.jl - I haven't known about it

**Comment by schlichtanders** [comment]
I leave this open for my TODO list as long as I don't have good reason to keep the name or a good alternative one

**Comment by schlichtanders** [comment]
@JeffreySarnoff I found a name and would like to hear your thought on it: `WhereTraits.jl`

**Comment by JeffreySarnoff** [comment]
I like it.
